name: CI

on:
  push:
    branches: [ dev-gitactions, dev-fix]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Lint
      if: github.event_name == 'pull_request'
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        pip install black
        pip install mypy
        python setup.py install
        black --version
        git diff --name-only $BASE_SHA..$HEAD_SHA | grep "*.py" | xargs black --diff --check
        mypy --version
        mypy pyevmasm
        
  test37:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Run Tests 37
      run: |
        python setup.py install
        python -m unittest discover "tests/"

  test27:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Run Tests 27
      run: |
        python setup.py install
        python -m unittest discover "tests/"

